version: '3.8'

services:
  soya-insights:
    container_name: soya-insights
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_BASEURLPATH=/soya-insights
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/soya-insights/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
